### ISSUE TITLE
Help using it

### ISSUE THREAD

**Issue by onealhtml** [FaithBeam/YMouseButtonControl#1]
Hello, I'm looking forward to download your application. I'm trying to move to linux, but "X mouse Button" is very useful in Windows. Do you have any release date?

Thanks in advance!
onealhtml

**Comment by FaithBeam** [comment]
@onealhtml Sorry for going AWOL. I have an initial release on the [releases](https://github.com/FaithBeam/YMouseButtonControl/releases) page. There will be bugs as a heads-up.
