### ISSUE TITLE
Responses get slow after a while

### ISSUE THREAD

**Issue by BramVanBerkel** [FaithBeam/YMouseButtonControl#11]
Hi there, thanks for this great piece of software! I am currently using it to switch over to linux.

The problem i'm having is when i have been using it for about an hour the responses suddenly get increasingly more slow. up to a couple of seconds. I have to restart the program again to get fast responses back.
I also noticed the process is using a lot of Virtual memory, i don't know if that could be the cause of the problem i'm having:

![Screenshot from 2024-08-02 22-54-54](https://github.com/user-attachments/assets/09d3354c-9e91-4edb-8ee5-00ea74351063)

**Comment by FaithBeam** [comment]
@BramVanBerkel 
It's likely there is a memory leak somewhere. Can you show me what you have for layer 1 please?

**Comment by BramVanBerkel** [comment]
@FaithBeam Sure, i only swap mouse button 4 and 5 for esc and space, in a specific Java application
![Screenshot from 2024-08-04 20-48-52](https://github.com/user-attachments/assets/70ac5b59-94a3-432e-a327-37e17acfd8b6)

**Comment by FaithBeam** [comment]
Thank you, I'll take a look.

**Comment by FaithBeam** [comment]
Just opening the app sets the virtual memory at a ridiculous number which is odd. 
![image](https://github.com/user-attachments/assets/16687862-62a4-486c-9599-d26d91110c9b)

Virtual memory on Windows seems normal.
![image](https://github.com/user-attachments/assets/f030b602-2bdf-46c4-8d15-07514ea87a9c)

**Comment by FaithBeam** [comment]
@BramVanBerkel 
Try [0.9.2](https://github.com/FaithBeam/YMouseButtonControl/releases/tag/0.9.2).
I updated Sharphook, the library ymousebuttoncontrol uses to handle mouse and keyboard. It had an [update](https://github.com/TolikPylypchuk/SharpHook/releases/tag/v5.3.7) a month ago to fix a memory leak.
That doesn't fix the high virtual memory usage but I think that is a dotnet runtime [issue](https://github.com/dotnet/runtime/issues/9199).

Let me know if that fixes this issue.

**Comment by BramVanBerkel** [comment]
@FaithBeam Thanks! I've installed it and will be testing it, it'll maybe take a couple of days before i get the chance to play enough to encounter the problem. I'll get back to you!

**Comment by FaithBeam** [comment]
@BramVanBerkel Sounds good, thank you!

**Comment by BramVanBerkel** [comment]
Sorry that it took a while, had a vacation in between. Encountered no issues so far, so i think this issue can be closed safely!

I do have another request about the ability to launch the app in the background for login. Should i open a new ticket for that?

**Comment by FaithBeam** [comment]
> Sorry that it took a while, had a vacation in between. Encountered no issues so far, so i think this issue can be closed safely!

No worries, I too got back from vacation a few days ago and hope yours was enjoyable! :)

> I do have another request about the ability to launch the app in the background for login. Should i open a new ticket for that?

That's a good request! Thank you! I've opened #13 for this feature. Feel free to give feedback or not there.
