### ISSUE TITLE
Can't see what each button does in dark mode unless hovered

### ISSUE THREAD

**Issue by Ladripper** [FaithBeam/YMouseButtonControl#16]
Tried both building from source and the release version on Arch linux with KDE Wayland, the boxes are just solid white unless hovered, then shows as intended. Alternatively a toggle to switch from dark to light mode independent of OS setting
![with mouse](https://github.com/user-attachments/assets/6b567157-a835-431c-827c-6049166359a9)
![no mouse](https://github.com/user-attachments/assets/e3333639-6c20-4021-b22e-47ac45f80fc4)

**Comment by FaithBeam** [comment]
Thank you for the bug report! I'll begin work on this when I finish #15.

**Comment by FaithBeam** [comment]
@Ladripper I've added theme support in #18. It doesn't fix the default broken theming, but it does give you a work around to select light or dark theme from the global settings menu. Check #18 for gif.
