### ISSUE TITLE
Sending comands while button is presset doenst actually remove the bindinds when the button is not pressed anymore

### ISSUE THREAD

**Issue by josefelbez** [FaithBeam/YMouseButtonControl#9]
Hi, im using this as a macro for a game, on windows we have the XMouseButtonControl that works just fine and using the 7 Sticky I can lock the macro and unlock by pressing again, but with YMouseButtonControl if I do the same It wont reset the macro will just print another time the commands and results in memory leak freezing the whole os.

Also the ui is a bit broken when the macro keys are too big
![image](https://github.com/FaithBeam/YMouseButtonControl/assets/12129203/0b9f3ee2-c779-49ce-8183-30532419cea4)

**Comment by FaithBeam** [comment]
@josefelbez Hello! Thank you for the bug report!

* What is your OS
* Can you please copy and paste the entire string for the sticky repeat
* How long does it take for your OS to freeze when using the macro

Try release [0.9.1](https://github.com/FaithBeam/YMouseButtonControl/releases/tag/0.9.1). 
* Set max width to the application which will prevent it from expanding unbounded
* Fix the repeat delay not actually applying to the individual keys in sticky repeat
* Change how cancelling the sticky repeat service works so it should stop quicker. It's not perfect, in my test it still sends one extra character which isn't ideal, but way better than sending the entire remaining stack of characters and quitting

**Comment by josefelbez** [comment]
Hey thanks for the response, i tried with the new version and it works as expected now!

Not sure if was a missconfiguration of mine before or the new version fixes it, anyways thanks for your time!

The ui is fixed as well btw
